import { BibimbapIcon, BurgerIcon, InstantIcon, KimbapIcon, MysteryIcon, NoodleIcon, SteakIcon, SushiIcon } from "./Icons";

export const CATEGORIES = [
  { id: '한식', sub: '든든하게!', icon: BibimbapIcon },
  { id: '중식', sub: '기름지게!', icon: NoodleIcon },
  { id: '일식', sub: '깔끔하게!', icon: SushiIcon },
  { id: '양식', sub: '고급지게!', icon: SteakIcon },
  { id: '분식', sub: '추억 삼아!', icon: KimbapIcon },
  { id: '패스트푸드', sub: '빠르게!', icon: BurgerIcon },
  { id: '간편식', sub: '간단하게!', icon: InstantIcon },
  { id: '기타', sub: '이도 저도?', icon: MysteryIcon },
];


export const FOODS: Record<string, any[]> = {
    '한식': [
      { name: '비빔밥', cat: '한식', icon: 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14/assets/svg/1f35a.svg' },
      { name: '삼겹살', cat: '한식', icon: 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14/assets/svg/1f969.svg' },
      { name: '김치찌개', cat: '한식', icon: 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14/assets/svg/1f372.svg' },
      { name: '불고기', cat: '한식', icon: 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14/assets/svg/1f356.svg' },
      { name: '냉면', cat: '한식', icon: 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14/assets/svg/1f35c.svg' },
      { name: '갈비탕', cat: '한식', icon: 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14/assets/svg/1f357.svg' },
      { name: '순대국밥', cat: '한식', icon: 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14/assets/svg/1f35b.svg' },
      { name: '된장찌개', cat: '한식', icon: 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14/assets/svg/1f372.svg' },
      { name: '잡채', cat: '한식', icon: 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14/assets/svg/1f35d.svg' },
      { name: '전골', cat: '한식', icon: 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14/assets/svg/1f371.svg' },
      { name: '삼계탕', cat: '한식', icon: 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14/assets/svg/1f357.svg' },
      { name: '갈비구이', cat: '한식', icon: 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14/assets/svg/1f356.svg' },
      { name: '해물파전', cat: '한식', icon: 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14/assets/svg/1f95e.svg' },
      { name: '제육볶음', cat: '한식', icon: 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14/assets/svg/1f969.svg' },
      { name: '순두부찌개',cat:'한식', icon: 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14/assets/svg/1f372.svg' },
      { name: '육개장', cat: '한식', icon: 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14/assets/svg/1f35b.svg' },
    ],
    '중식': [
      { name: '짜장면', cat: '중식', icon: 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14/assets/svg/1f35c.svg' },
      { name: '짬뽕', cat: '중식', icon: 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14/assets/svg/1f35c.svg' },
      { name: '탕수육', cat: '중식', icon: 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14/assets/svg/1f357.svg' },
      { name: '마파두부', cat: '중식', icon: 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14/assets/svg/1f372.svg' },
      { name: '볶음밥', cat: '중식', icon: 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14/assets/svg/1f35a.svg' },
      { name: '깐풍기', cat: '중식', icon: 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14/assets/svg/1f357.svg' },
      { name: '딤섬', cat: '중식', icon: 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14/assets/svg/1f95f.svg' },
      { name: '마라탕', cat: '중식', icon: 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14/assets/svg/1f372.svg' },
      { name: '홍소육', cat: '중식', icon: 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14/assets/svg/1f356.svg' },
      { name: '군만두', cat: '중식', icon: 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14/assets/svg/1f95f.svg' },
      { name: '쟁반짜장', cat: '중식', icon: 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14/assets/svg/1f35d.svg' },
      { name: '유린기', cat: '중식', icon: 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14/assets/svg/1f357.svg' },
      { name: '팔보채', cat: '중식', icon: 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14/assets/svg/1f364.svg' },
      { name: '라조기', cat: '중식', icon: 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14/assets/svg/1f357.svg' },
      { name: '훠궈', cat: '중식', icon: 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14/assets/svg/1f372.svg' },
      { name: '양꼬치', cat: '중식', icon: 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14/assets/svg/1f969.svg' },
    ],
    '일식': [
      { name: '초밥', cat: '일식', icon: 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14/assets/svg/1f363.svg' },
      { name: '라멘', cat: '일식', icon: 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14/assets/svg/1f35c.svg' },
      { name: '우동', cat: '일식', icon: 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14/assets/svg/1f35c.svg' },
      { name: '돈카츠', cat: '일식', icon: 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14/assets/svg/1f95e.svg' },
      { name: '텐동', cat: '일식', icon: 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14/assets/svg/1f364.svg' },
      { name: '타코야키', cat: '일식', icon: 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14/assets/svg/1f361.svg' },
      { name: '야키토리', cat: '일식', icon: 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14/assets/svg/1f362.svg' },
      { name: '가이세키', cat: '일식', icon: 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14/assets/svg/1f371.svg' },
      { name: '소바', cat: '일식', icon: 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14/assets/svg/1f35c.svg' },
      { name: '오니기리', cat: '일식', icon: 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14/assets/svg/1f359.svg' },
      { name: '오야코동', cat: '일식', icon: 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14/assets/svg/1f35a.svg' },
      { name: '규동', cat: '일식', icon: 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14/assets/svg/1f35a.svg' },
      { name: '차슈덮밥', cat: '일식', icon: 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14/assets/svg/1f35a.svg' },
      { name: '낫토정식', cat: '일식', icon: 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14/assets/svg/1f371.svg' },
      { name: '야키소바', cat: '일식', icon: 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14/assets/svg/1f35d.svg' },
      { name: '된장국정식', cat: '일식', icon: 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14/assets/svg/1f371.svg' },
    ],
    '양식': [
      { name: '스테이크', cat: '양식', icon: 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14/assets/svg/1f969.svg' },
      { name: '파스타', cat: '양식', icon: 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14/assets/svg/1f35d.svg' },
      { name: '피자', cat: '양식', icon: 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14/assets/svg/1f355.svg' },
      { name: '리조또', cat: '양식', icon: 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14/assets/svg/1f35a.svg' },
      { name: '그라탱', cat: '양식', icon: 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14/assets/svg/1f370.svg' },
      { name: '연어스테이크', cat: '양식', icon: 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14/assets/svg/1f41f.svg' },
      { name: '크림수프', cat: '양식', icon: 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14/assets/svg/1f35b.svg' },
      { name: '샐러드', cat: '양식', icon: 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14/assets/svg/1f957.svg' },
      { name: '오믈렛', cat: '양식', icon: 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14/assets/svg/1f373.svg' },
      { name: '폭찹', cat: '양식', icon: 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14/assets/svg/1f356.svg' },
      { name: '라자냐', cat: '양식', icon: 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14/assets/svg/1f355.svg' },
      { name: '치킨윙', cat: '양식', icon: 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14/assets/svg/1f357.svg' },
      { name: '비프스튜', cat: '양식', icon: 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14/assets/svg/1f372.svg' },
      { name: '뇨끼', cat: '양식', icon: 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14/assets/svg/1f35d.svg' },
      { name: '클램차우더', cat: '양식', icon: 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14/assets/svg/1f35b.svg' },
    ],
    '분식': [
      { name: '김밥', cat: '분식', icon: 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14/assets/svg/1f359.svg' },
      { name: '떡볶이', cat: '분식', icon: 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14/assets/svg/1f35c.svg' },
      { name: '순대', cat: '분식', icon: 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14/assets/svg/1f321.svg' },
      { name: '튀김', cat: '분식', icon: 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14/assets/svg/1f364.svg' },
      { name: '라볶이', cat: '분식', icon: 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14/assets/svg/1f35c.svg' },
      { name: '핫도그', cat: '분식', icon: 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14/assets/svg/1f32d.svg' },
      { name: '오뎅', cat: '분식', icon: 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14/assets/svg/1f362.svg' },
      { name: '만두', cat: '분식', icon: 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14/assets/svg/1f95f.svg' },
      { name: '떡꼬치', cat: '분식', icon: 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14/assets/svg/1f362.svg' },
      { name: '어묵탕', cat: '분식', icon: 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14/assets/svg/1f372.svg' },
    ],
    '패스트푸드': [
      { name: '빅맥', cat: '패스트푸드', icon: 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14/assets/svg/1f354.svg' },
      { name: '와퍼', cat: '패스트푸드', icon: 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14/assets/svg/1f354.svg' },
      { name: '감자튀김', cat: '패스트푸드', icon: 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14/assets/svg/1f35f.svg' },
      { name: '치킨버거', cat: '패스트푸드', icon: 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14/assets/svg/1f354.svg' },
      { name: '핫도그', cat: '패스트푸드', icon: 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14/assets/svg/1f32d.svg' },
      { name: '치즈버거', cat: '패스트푸드', icon: 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14/assets/svg/1f354.svg' },
      { name: '콜라', cat: '패스트푸드', icon: 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14/assets/svg/1f964.svg' },
      { name: '너겟', cat: '패스트푸드', icon: 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14/assets/svg/1f357.svg' },
    ],
    '간편식': [
      { name: '컵라면', cat: '간편식', icon: 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14/assets/svg/1f35c.svg' },
      { name: '삼각김밥', cat: '간편식', icon: 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14/assets/svg/1f359.svg' },
      { name: '샌드위치', cat: '간편식', icon: 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14/assets/svg/1f96a.svg' },
      { name: '도시락', cat: '간편식', icon: 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14/assets/svg/1f371.svg' },
    ],
    '기타': [
      { name: '타코', cat: '기타', icon: 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14/assets/svg/1f32e.svg' },
      { name: '케밥', cat: '기타', icon: 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14/assets/svg/1f32f.svg' },
      { name: '쌀국수', cat: '기타', icon: 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14/assets/svg/1f35c.svg' },
      { name: '커리', cat: '기타', icon: 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14/assets/svg/1f35b.svg' },
    ],
  };