name: Foodia CI/CD

on:
  push:
    branches: [ "main" ] 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/foodia
            git fetch --all
            git reset --hard origin/main || exit 1
            npm install
            npm run build || exit 1    
            sudo fuser -k 3000/tcp || true
            pm2 delete foodia || true
            pm2 start npm --name "foodia" -- start
            pm2 save
